### ISSUE TITLE
site en vitepress

### ISSUE THREAD

**Issue by crguezl** [gh-cli-for-education/gh-education#9]
@alu0101102726 

Mira en la rama `casiano` y despliega. En la sección `debug` verás como 
acceder a `site` y `pages`

<img width="1451" alt="Captura de pantalla 2022-12-30 a las 13 33 22" src="https://user-images.githubusercontent.com/1142554/210075800-86c4cfe5-081d-4b8f-8999-daa44e1d29ea.png">

**Comment by alu0101102726** [comment]
He estado comprobando toda esta información, y hay un problema, el site es readonly, por ende no se puede modificar ni añadir o eliminar elementos dentro de el

**Comment by crguezl** [comment]
Si, el `site` no nos sirve @alu0101102726

**Comment by crguezl** [comment]
Es que `site` solo existe en "building" time y lo que queremos hacer es en el cliente
